
FROM node:20-alpine as build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# Nginx commonly used to serve static files - the asset images, HTML, CSS, JS files aka frontend
# Load balancing, separation of concern where Node server can just handle backend
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
