
FROM node:20-alpine as build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# Stage 2: Serve the React app using an Nginx server
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
