version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - node-server

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
